# Dockerfile for running org-grep. This is to make it convenient to test searcher in
# the same network as a production environment.
#
# $ docker build -f Dockerfile.org-grep -t org-grep .
# $ docker run --rm=true org-grep github.com/sourcegraph/go-langserver vscode
FROM python:3-alpine@sha256:ba0abe942dc68a32f24294b2ce6e7116d2082e5fd9ad532df8a47de31292fab4

RUN pip install requests==2.18.4

COPY org-grep.py /org-grep.py

ENTRYPOINT ["python", "/org-grep.py"]
